### ISSUE TITLE
initDisplay() and drawGui() are not called after connection to JDY-33 module

### ISSUE THREAD

**Issue by v2e** [ArminJo/android-blue-display#1]
Hello!
I use a JDY-33 bluetooth module, similar to HC-05.

I started with the `BlueDisplayBlink` example, and I was able to connect to the module with my phone, and see the blinking circle in the screen. However, there was no pushbutton in the screen.

After some tries, I found out that the `initDisplay()` and `drawGui()` functions were apparently never called. If I call them manually inside my `loop()` function (just to test), the pushbutton appears in the screen.

So it looks like these functions are not called after the connection is established.

I installed the BlueDisplay library v.4.0.1 from the Arduino library manager.
The Android app is v.4.3.1 downloaded from here: https://github.com/ArminJo/android-blue-display/tree/master/APKs

**Comment by ArminJo** [comment]
Sorry, I forgot to commit the latest APK 4.3.3 available at the Playstore.
I just tested BlueDisplayBlink, and it runs as expected (with button).

```
/**
 * initCommunication() sets callback handler and calls host for requestMaxCanvasSize().
 * If host is connected, this results in a EVENT_REQUESTED_DATA_CANVAS_SIZE callback event,
 * which sends display size and local timestamp. This event calls the ConnectCallback as well as the RedrawCallback.
 *
 * Waits for 300 ms for connection to be established
 *
 * Reorientation callback function is only required if we have a responsive layout,
 * since connect and reorientation event also calls the redraw callback.
 *
 * For ESP32 and after power on at other platforms, Bluetooth is just enabled here,
 * but the android app (host) is not manually (re)connected to us, so we are most likely not connected here.
 * In this case, the periodic call of checkAndHandleEvents() in the main loop catches the connection build up message
 * from the android app at the time of manual (re)connection and in turn calls the initDisplay() and drawGui() functions.
 */
```

**Comment by v2e** [comment]
I am sorry. It turned out that my Arduino board did not receive the data from the bluetooth module correctly. So it was a hardware problem. Now that I have traced it down, the BlueDisplayBlink example works fine.

Thanks!
